# name: learn-github-actions
# on: [push]
# jobs:
#   check-python-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v3
#         with:
#           python-version: '3.9'
#       - run: python --version
#       - name: python script
#         run:  python python.py

# name: learn-github-actions
# on: [push]
# jobs:
#  check-python-version:
#   strategy: 
#    matrix:
#     os: [ubuntu-latest,windows latest,macos-latest]
#     runs-on: ${{matrix.os}}
#      steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v3 
#      with: 
#       python-version: '3.6'
#       - run: python --version

# name: main
# on: push
# jobs:
#  job1:
#    runs-on: ubuntu-latest
#    env:
#     name1: "saloni"
#    steps:
#      - name: step 1
#        run: echo "The name1 is:$name1"
#  job2:
#    runs-on: ubuntu-latest
#    steps:
#      - name: step 2 
#        run: echo "The name2 is:$name2"


name: First Cron Job

on: push
#   schedule:
#    - cron: "*/1 * * * *"
jobs:
  build:
    runs-on: self-hosted

    steps:
      # - uses: action/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

